baseurl = "https://example.org/"
languageCode = "en-us"
title = "Website Simply"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Greg Doig"
    site_description = "Another Awesome Website by Greg Doig."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Website Simply"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "rangerdoig"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "rangerd"
    gplus     = ""
